/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Injectable } from '@angular/core';

/**
 * Provides the AlgoJudgeAdminApiConfiguration configuration object with a given root URL.
 */
export function provideAlgoJudgeAdminApiConfiguration(rootUrl: string) {
  var config = new AlgoJudgeAdminApiConfiguration();
  config.rootUrl = rootUrl;
  return {
    provide: AlgoJudgeAdminApiConfiguration,
    useValue: config
  };
}

/**
 * Global configuration
 */
@Injectable({
  providedIn: 'root',
})
export class AlgoJudgeAdminApiConfiguration {
  rootUrl: string = '';
}

