/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ContentBatchResponse } from '../../models/content-batch-response';
import { CreateContentBatchRequest } from '../../models/create-content-batch-request';

export interface ApiInternalAdminContentBatchesPost$Plain$Params {
      body: CreateContentBatchRequest
}

export function apiInternalAdminContentBatchesPost$Plain(http: HttpClient, rootUrl: string, params: ApiInternalAdminContentBatchesPost$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<ContentBatchResponse>> {
  const rb = new RequestBuilder(rootUrl, apiInternalAdminContentBatchesPost$Plain.PATH, 'post');
  if (params) {
    rb.body(params.body, 'text/json');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ContentBatchResponse>;
    })
  );
}

apiInternalAdminContentBatchesPost$Plain.PATH = '/api/internal/admin/content-batches';
