/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ContentBatchStatus } from '../../models/content-batch-status';
import { PagedResponseOfContentBatchListItemResponse } from '../../models/paged-response-of-content-batch-list-item-response';

export interface ApiInternalAdminContentBatchesGet$Plain$Params {
  PageNumber?: (number | string);
  PageSize?: (number | string);
  Status?: ContentBatchStatus;
}

export function apiInternalAdminContentBatchesGet$Plain(http: HttpClient, rootUrl: string, params?: ApiInternalAdminContentBatchesGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<PagedResponseOfContentBatchListItemResponse>> {
  const rb = new RequestBuilder(rootUrl, apiInternalAdminContentBatchesGet$Plain.PATH, 'get');
  if (params) {
    rb.query('PageNumber', params.PageNumber, {});
    rb.query('PageSize', params.PageSize, {});
    rb.query('Status', params.Status, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PagedResponseOfContentBatchListItemResponse>;
    })
  );
}

apiInternalAdminContentBatchesGet$Plain.PATH = '/api/internal/admin/content-batches';
