/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ContentBatchResponse } from '../../models/content-batch-response';

export interface ApiInternalAdminContentBatchesBatchIdResumePost$Json$Params {
  batchId: string;
}

export function apiInternalAdminContentBatchesBatchIdResumePost$Json(http: HttpClient, rootUrl: string, params: ApiInternalAdminContentBatchesBatchIdResumePost$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<ContentBatchResponse>> {
  const rb = new RequestBuilder(rootUrl, apiInternalAdminContentBatchesBatchIdResumePost$Json.PATH, 'post');
  if (params) {
    rb.path('batchId', params.batchId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ContentBatchResponse>;
    })
  );
}

apiInternalAdminContentBatchesBatchIdResumePost$Json.PATH = '/api/internal/admin/content-batches/{batchId}/resume';
