/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ContentBatchResponse } from '../../models/content-batch-response';
import { PublishContentBatchRequest } from '../../models/publish-content-batch-request';

export interface ApiInternalAdminContentBatchesBatchIdPublishPost$Json$Params {
  batchId: string;
      body: PublishContentBatchRequest
}

export function apiInternalAdminContentBatchesBatchIdPublishPost$Json(http: HttpClient, rootUrl: string, params: ApiInternalAdminContentBatchesBatchIdPublishPost$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<ContentBatchResponse>> {
  const rb = new RequestBuilder(rootUrl, apiInternalAdminContentBatchesBatchIdPublishPost$Json.PATH, 'post');
  if (params) {
    rb.path('batchId', params.batchId, {});
    rb.body(params.body, 'text/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ContentBatchResponse>;
    })
  );
}

apiInternalAdminContentBatchesBatchIdPublishPost$Json.PATH = '/api/internal/admin/content-batches/{batchId}/publish';
