/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ProblemDraftResponse } from '../../models/problem-draft-response';
import { UpdateProblemDraftRequest } from '../../models/update-problem-draft-request';

export interface ApiInternalAdminProblemDraftsRevisionIdMetadataPut$Plain$Params {
  revisionId: string;
      body: UpdateProblemDraftRequest
}

export function apiInternalAdminProblemDraftsRevisionIdMetadataPut$Plain(http: HttpClient, rootUrl: string, params: ApiInternalAdminProblemDraftsRevisionIdMetadataPut$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<ProblemDraftResponse>> {
  const rb = new RequestBuilder(rootUrl, apiInternalAdminProblemDraftsRevisionIdMetadataPut$Plain.PATH, 'put');
  if (params) {
    rb.path('revisionId', params.revisionId, {});
    rb.body(params.body, 'text/json');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ProblemDraftResponse>;
    })
  );
}

apiInternalAdminProblemDraftsRevisionIdMetadataPut$Plain.PATH = '/api/internal/admin/problem-drafts/{revisionId}/metadata';
