/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateProblemDraftRequest } from '../../models/create-problem-draft-request';
import { ProblemDraftResponse } from '../../models/problem-draft-response';

export interface ApiInternalAdminProblemDraftsPost$Plain$Params {
      body: CreateProblemDraftRequest
}

export function apiInternalAdminProblemDraftsPost$Plain(http: HttpClient, rootUrl: string, params: ApiInternalAdminProblemDraftsPost$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<ProblemDraftResponse>> {
  const rb = new RequestBuilder(rootUrl, apiInternalAdminProblemDraftsPost$Plain.PATH, 'post');
  if (params) {
    rb.body(params.body, 'text/json');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ProblemDraftResponse>;
    })
  );
}

apiInternalAdminProblemDraftsPost$Plain.PATH = '/api/internal/admin/problem-drafts';
