/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ProblemDraftResponse } from '../../models/problem-draft-response';

export interface ApiInternalAdminProblemDraftsRevisionIdGet$Json$Params {
  revisionId: string;
}

export function apiInternalAdminProblemDraftsRevisionIdGet$Json(http: HttpClient, rootUrl: string, params: ApiInternalAdminProblemDraftsRevisionIdGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<ProblemDraftResponse>> {
  const rb = new RequestBuilder(rootUrl, apiInternalAdminProblemDraftsRevisionIdGet$Json.PATH, 'get');
  if (params) {
    rb.path('revisionId', params.revisionId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ProblemDraftResponse>;
    })
  );
}

apiInternalAdminProblemDraftsRevisionIdGet$Json.PATH = '/api/internal/admin/problem-drafts/{revisionId}';
