/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ContentGenerationStatusResponse } from '../../models/content-generation-status-response';

export interface ApiInternalAdminProblemDraftsRevisionIdGenerationPost$Json$Params {
  revisionId: string;
}

export function apiInternalAdminProblemDraftsRevisionIdGenerationPost$Json(http: HttpClient, rootUrl: string, params: ApiInternalAdminProblemDraftsRevisionIdGenerationPost$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<ContentGenerationStatusResponse>> {
  const rb = new RequestBuilder(rootUrl, apiInternalAdminProblemDraftsRevisionIdGenerationPost$Json.PATH, 'post');
  if (params) {
    rb.path('revisionId', params.revisionId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ContentGenerationStatusResponse>;
    })
  );
}

apiInternalAdminProblemDraftsRevisionIdGenerationPost$Json.PATH = '/api/internal/admin/problem-drafts/{revisionId}/generation';
