/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ProblemDraftResponse } from '../../models/problem-draft-response';
import { UpdateSuiteQualityPolicyRequest } from '../../models/update-suite-quality-policy-request';

export interface ApiInternalAdminProblemDraftsRevisionIdQualityPolicyPut$Json$Params {
  revisionId: string;
      body: UpdateSuiteQualityPolicyRequest
}

export function apiInternalAdminProblemDraftsRevisionIdQualityPolicyPut$Json(http: HttpClient, rootUrl: string, params: ApiInternalAdminProblemDraftsRevisionIdQualityPolicyPut$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<ProblemDraftResponse>> {
  const rb = new RequestBuilder(rootUrl, apiInternalAdminProblemDraftsRevisionIdQualityPolicyPut$Json.PATH, 'put');
  if (params) {
    rb.path('revisionId', params.revisionId, {});
    rb.body(params.body, 'text/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ProblemDraftResponse>;
    })
  );
}

apiInternalAdminProblemDraftsRevisionIdQualityPolicyPut$Json.PATH = '/api/internal/admin/problem-drafts/{revisionId}/quality-policy';
