/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ContentGenerationStatusResponse } from '../../models/content-generation-status-response';

export interface ApiInternalAdminProblemDraftsRevisionIdGenerationGet$Plain$Params {
  revisionId: string;
}

export function apiInternalAdminProblemDraftsRevisionIdGenerationGet$Plain(http: HttpClient, rootUrl: string, params: ApiInternalAdminProblemDraftsRevisionIdGenerationGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<ContentGenerationStatusResponse>> {
  const rb = new RequestBuilder(rootUrl, apiInternalAdminProblemDraftsRevisionIdGenerationGet$Plain.PATH, 'get');
  if (params) {
    rb.path('revisionId', params.revisionId, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ContentGenerationStatusResponse>;
    })
  );
}

apiInternalAdminProblemDraftsRevisionIdGenerationGet$Plain.PATH = '/api/internal/admin/problem-drafts/{revisionId}/generation';
