// <auto-generated />
using System;
using AlgoJudge.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AlgoJudge.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260728155652_AddContentBatchOperations")]
    partial class AddContentBatchOperations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AlgoJudge.Domain.Entities.AuthoringTestCase", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ExpectedOutput")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Input")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("KilledWrongSolutionsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer");

                    b.Property<Guid>("RevisionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Seed")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RevisionId", "Name")
                        .IsUnique();

                    b.HasIndex("RevisionId", "Ordinal")
                        .IsUnique();

                    b.ToTable("AuthoringTestCases", null, t =>
                        {
                            t.HasCheckConstraint("CK_AuthoringTestCase_Group", "\"Group\" IN ('handwritten', 'edge', 'random', 'adversarial', 'stress')");

                            t.HasCheckConstraint("CK_AuthoringTestCase_Ordinal", "\"Ordinal\" > 0");
                        });
                });

            modelBuilder.Entity("AlgoJudge.Domain.Entities.CodeRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<Guid?>("ClaimToken")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorOutput")
                        .HasColumnType("text");

                    b.Property<int>("ExecutionTimeMs")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Input")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("LeaseExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MemoryUsedKb")
                        .HasColumnType("integer");

                    b.Property<int>("ProblemId")
                        .HasColumnType("integer");

                    b.Property<string>("SourceCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StandardOutput")
                        .HasColumnType("text");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("WorkerId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .IsDescending();

                    b.HasIndex("ProblemId");

                    b.HasIndex("UserId");

                    b.HasIndex("Status", "LeaseExpiresAt");

                    b.HasIndex("Status", "CreatedAt", "Id");

                    b.ToTable("CodeRuns", null, t =>
                        {
                            t.HasCheckConstraint("CK_CodeRun_AttemptCount", "\"AttemptCount\" >= 0");

                            t.HasCheckConstraint("CK_CodeRun_RunningClaim", "\"Status\" <> 2 OR (\"WorkerId\" IS NOT NULL AND \"ClaimToken\" IS NOT NULL AND \"LeaseExpiresAt\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("AlgoJudge.Domain.Entities.ContentBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CatalogName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId", "CreatedAt");

                    b.HasIndex("Status", "UpdatedAt");

                    b.ToTable("ContentBatches", null, t =>
                        {
                            t.HasCheckConstraint("CK_ContentBatch_Status", "\"Status\" IN (0, 1, 2, 3, 4, 5)");
                        });
                });

            modelBuilder.Entity("AlgoJudge.Domain.Entities.ContentBatchAuditEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("AdminUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<int?>("ProblemId")
                        .HasColumnType("integer");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid?>("RevisionId")
                        .HasColumnType("uuid");

                    b.Property<string>("SafeFailureCategory")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("AdminUserId", "CreatedAt");

                    b.HasIndex("BatchId", "CreatedAt");

                    b.ToTable("ContentBatchAuditEntries", (string)null);
                });

            modelBuilder.Entity("AlgoJudge.Domain.Entities.ContentBatchItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Action")
                        .HasColumnType("integer");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uuid");

                    b.Property<string>("CatalogPath")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("ConstraintsMarkdown")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContentHash")
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .IsFixedLength();

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DefinitionJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GeneratorParametersJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("MemoryLimitKb")
                        .HasColumnType("integer");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer");

                    b.Property<int?>("ProblemId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("RevisionId")
                        .HasColumnType("uuid");

                    b.Property<string>("SafeFailureCategory")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("SafeFailureMessage")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("SamplesJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("StatementMarkdown")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TagsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("TimeLimitMs")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("ProblemId");

                    b.HasIndex("RevisionId");

                    b.HasIndex("BatchId", "Ordinal")
                        .IsUnique();

                    b.HasIndex("BatchId", "Status");

                    b.HasIndex("Slug", "ContentHash");

                    b.ToTable("ContentBatchItems", null, t =>
                        {
                            t.HasCheckConstraint("CK_ContentBatchItem_Action", "\"Action\" IN (0, 1, 2, 3)");

                            t.HasCheckConstraint("CK_ContentBatchItem_Ordinal", "\"Ordinal\" > 0");

                            t.HasCheckConstraint("CK_ContentBatchItem_Resolution", "(\"Status\" IN (1, 2, 3, 5) AND \"ProblemId\" IS NOT NULL AND \"RevisionId\" IS NOT NULL) OR \"Status\" IN (0, 4, 6)");

                            t.HasCheckConstraint("CK_ContentBatchItem_Status", "\"Status\" IN (0, 1, 2, 3, 4, 5, 6)");
                        });
                });

            modelBuilder.Entity("AlgoJudge.Domain.Entities.ContentGenerationJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<Guid?>("BatchItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ClaimToken")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DefinitionSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .IsFixedLength();

                    b.Property<string>("DefinitionSnapshotJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LeaseExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MemoryLimitKb")
                        .HasColumnType("integer");

                    b.Property<Guid>("RevisionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("TimeLimitMs")
                        .HasColumnType("integer");

                    b.Property<string>("WorkerId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("BatchItemId");

                    b.HasIndex("LeaseExpiresAt");

                    b.HasIndex("RevisionId")
                        .IsUnique()
                        .HasFilter("\"Status\" IN (0, 1)");

                    b.HasIndex("Status", "CreatedAt");

                    b.ToTable("ContentGenerationJobs", null, t =>
                        {
                            t.HasCheckConstraint("CK_ContentGenerationJob_Attempts", "\"AttemptCount\" >= 0");

                            t.HasCheckConstraint("CK_ContentGenerationJob_Claim", "(\"Status\" = 1 AND \"WorkerId\" IS NOT NULL AND \"ClaimToken\" IS NOT NULL AND \"LeaseExpiresAt\" IS NOT NULL) OR (\"Status\" <> 1 AND \"WorkerId\" IS NULL AND \"ClaimToken\" IS NULL AND \"LeaseExpiresAt\" IS NULL)");

                            t.HasCheckConstraint("CK_ContentGenerationJob_Status", "\"Status\" IN (0, 1, 2, 3)");
                        });
                });

            modelBuilder.Entity("AlgoJudge.Domain.Entities.JudgeTestCase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ExpectedOutput")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Input")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer");

                    b.Property<int>("ProblemId")
                        .HasColumnType("integer");

                    b.Property<int>("SystemTestSuiteVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("ProblemId", "SystemTestSuiteVersion", "Ordinal")
                        .IsUnique();

                    b.ToTable("JudgeTestCases", null, t =>
                        {
                            t.HasCheckConstraint("CK_JudgeTestCase_Ordinal", "\"Ordinal\" > 0");

                            t.HasCheckConstraint("CK_JudgeTestCase_SystemTestSuiteVersion", "\"SystemTestSuiteVersion\" > 0");
                        });
                });

            modelBuilder.Entity("AlgoJudge.Domain.Entities.Problem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ConstraintsMarkdown")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer");

                    b.Property<int>("ExecutionMode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("FunctionAdapterTemplate")
                        .HasColumnType("text");

                    b.Property<string>("FunctionSignatureJson")
                        .HasColumnType("jsonb");

                    b.Property<int>("JudgeVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<int>("MemoryLimitKb")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("StatementMarkdown")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<int>("TimeLimitMs")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("Status", "CreatedAt");

                    b.ToTable("Problems", null, t =>
                        {
                            t.HasCheckConstraint("CK_Problem_ExecutionMode", "\"ExecutionMode\" IN (0, 1)");

                            t.HasCheckConstraint("CK_Problem_FunctionConfiguration", "(\"ExecutionMode\" = 0 AND \"FunctionSignatureJson\" IS NULL AND \"FunctionAdapterTemplate\" IS NULL) OR (\"ExecutionMode\" = 1 AND \"FunctionSignatureJson\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_Problem_JudgeVersion", "\"JudgeVersion\" > 0");

                            t.HasCheckConstraint("CK_Problem_MemoryLimitKb", "\"MemoryLimitKb\" > 0");

                            t.HasCheckConstraint("CK_Problem_TimeLimitMs", "\"TimeLimitMs\" > 0");
                        });
                });

            modelBuilder.Entity("AlgoJudge.Domain.Entities.ProblemAuthoringRevision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("CandidateCaseCount")
                        .HasColumnType("integer");

                    b.Property<string>("CandidateStatisticsJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("CandidateSuiteSha256")
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .IsFixedLength();

                    b.Property<string>("CandidateToolchain")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<string>("ConstraintsMarkdown")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContentHash")
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .IsFixedLength();

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DefinitionJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("DefinitionSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .IsFixedLength();

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer");

                    b.Property<int>("MemoryLimitKb")
                        .HasColumnType("integer");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("ProblemId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RevisionNumber")
                        .HasColumnType("integer");

                    b.Property<string>("SamplesJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("StatementMarkdown")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TagsJson")
                        .HasColumnType("jsonb");

                    b.Property<int>("TimeLimitMs")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("ProblemId", "RevisionNumber")
                        .IsUnique();

                    b.HasIndex("OwnerUserId", "Status", "UpdatedAt");

                    b.ToTable("ProblemAuthoringRevisions", null, t =>
                        {
                            t.HasCheckConstraint("CK_AuthoringRevision_Candidate", "(\"Status\" IN (0, 1) AND \"CandidateSuiteSha256\" IS NULL AND \"CandidateCaseCount\" IS NULL) OR (\"Status\" IN (2, 3) AND \"CandidateSuiteSha256\" IS NOT NULL AND \"CandidateCaseCount\" > 0)");

                            t.HasCheckConstraint("CK_AuthoringRevision_MemoryLimit", "\"MemoryLimitKb\" > 0");

                            t.HasCheckConstraint("CK_AuthoringRevision_Number", "\"RevisionNumber\" > 0");

                            t.HasCheckConstraint("CK_AuthoringRevision_Status", "\"Status\" IN (0, 1, 2, 3)");

                            t.HasCheckConstraint("CK_AuthoringRevision_TimeLimit", "\"TimeLimitMs\" > 0");
                        });
                });

            modelBuilder.Entity("AlgoJudge.Domain.Entities.ProblemSample", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ExpectedOutput")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Explanation")
                        .HasColumnType("text");

                    b.Property<string>("Input")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer");

                    b.Property<int>("ProblemId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProblemId", "Ordinal")
                        .IsUnique();

                    b.ToTable("ProblemSamples", null, t =>
                        {
                            t.HasCheckConstraint("CK_ProblemSample_Ordinal", "\"Ordinal\" > 0");
                        });
                });

            modelBuilder.Entity("AlgoJudge.Domain.Entities.ProblemTag", b =>
                {
                    b.Property<int>("ProblemId")
                        .HasColumnType("integer");

                    b.Property<int>("TagId")
                        .HasColumnType("integer");

                    b.HasKey("ProblemId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("ProblemTags", (string)null);
                });

            modelBuilder.Entity("AlgoJudge.Domain.Entities.PublishedSystemTestSuite", b =>
                {
                    b.Property<int>("ProblemId")
                        .HasColumnType("integer");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.Property<double?>("AbsoluteTolerance")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("OutputCheckerKind")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<double?>("RelativeTolerance")
                        .HasColumnType("double precision");

                    b.HasKey("ProblemId", "Version");

                    b.ToTable("SystemTestSuites", null, t =>
                        {
                            t.HasCheckConstraint("CK_SystemTestSuite_OutputChecker", "\"OutputCheckerKind\" IN (0, 1, 2)");

                            t.HasCheckConstraint("CK_SystemTestSuite_OutputCheckerTolerance", "(\"OutputCheckerKind\" IN (0, 1) AND \"AbsoluteTolerance\" IS NULL AND \"RelativeTolerance\" IS NULL) OR (\"OutputCheckerKind\" = 2 AND \"AbsoluteTolerance\" IS NOT NULL AND \"RelativeTolerance\" IS NOT NULL AND \"AbsoluteTolerance\" NOT IN ('Infinity'::double precision, '-Infinity'::double precision, 'NaN'::double precision) AND \"RelativeTolerance\" NOT IN ('Infinity'::double precision, '-Infinity'::double precision, 'NaN'::double precision) AND \"AbsoluteTolerance\" >= 0 AND \"RelativeTolerance\" >= 0 AND (\"AbsoluteTolerance\" > 0 OR \"RelativeTolerance\" > 0))");

                            t.HasCheckConstraint("CK_SystemTestSuite_Version", "\"Version\" > 0");
                        });
                });

            modelBuilder.Entity("AlgoJudge.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("AlgoJudge.Domain.Entities.Submission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<Guid?>("ClaimToken")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ExecutionTime")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("LeaseExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MemoryUsed")
                        .HasColumnType("integer");

                    b.Property<string>("OriginalFileName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("ProblemId")
                        .HasColumnType("integer");

                    b.Property<string>("SourceCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("SystemTestSuiteVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("WorkerId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .IsDescending();

                    b.HasIndex("ProblemId");

                    b.HasIndex("UserId");

                    b.HasIndex("Status", "LeaseExpiresAt");

                    b.HasIndex("UserId", "ProblemId");

                    b.HasIndex("Status", "CreatedAt", "Id");

                    b.HasIndex("UserId", "Status", "ProblemId");

                    b.ToTable("Submissions", null, t =>
                        {
                            t.HasCheckConstraint("CK_Submission_AttemptCount", "\"AttemptCount\" >= 0");

                            t.HasCheckConstraint("CK_Submission_RunningClaim", "\"Status\" <> 2 OR (\"WorkerId\" IS NOT NULL AND \"ClaimToken\" IS NOT NULL AND \"LeaseExpiresAt\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_Submission_SystemTestSuiteVersion", "\"SystemTestSuiteVersion\" > 0");
                        });
                });

            modelBuilder.Entity("AlgoJudge.Domain.Entities.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Tags", (string)null);
                });

            modelBuilder.Entity("AlgoJudge.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("Role")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users", null, t =>
                        {
                            t.HasCheckConstraint("CK_User_Role", "\"Role\" IN (0, 1)");
                        });
                });

            modelBuilder.Entity("AlgoJudge.Domain.Entities.AuthoringTestCase", b =>
                {
                    b.HasOne("AlgoJudge.Domain.Entities.ProblemAuthoringRevision", "Revision")
                        .WithMany("CandidateTestCases")
                        .HasForeignKey("RevisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Revision");
                });

            modelBuilder.Entity("AlgoJudge.Domain.Entities.CodeRun", b =>
                {
                    b.HasOne("AlgoJudge.Domain.Entities.Problem", "Problem")
                        .WithMany("CodeRuns")
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlgoJudge.Domain.Entities.User", "User")
                        .WithMany("CodeRuns")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Problem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AlgoJudge.Domain.Entities.ContentBatch", b =>
                {
                    b.HasOne("AlgoJudge.Domain.Entities.User", "CreatedByUser")
                        .WithMany("ContentBatches")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("AlgoJudge.Domain.Entities.ContentBatchAuditEntry", b =>
                {
                    b.HasOne("AlgoJudge.Domain.Entities.User", "AdminUser")
                        .WithMany("ContentBatchAuditEntries")
                        .HasForeignKey("AdminUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AlgoJudge.Domain.Entities.ContentBatch", "Batch")
                        .WithMany("AuditEntries")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlgoJudge.Domain.Entities.ContentBatchItem", "Item")
                        .WithMany("AuditEntries")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("AdminUser");

                    b.Navigation("Batch");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("AlgoJudge.Domain.Entities.ContentBatchItem", b =>
                {
                    b.HasOne("AlgoJudge.Domain.Entities.ContentBatch", "Batch")
                        .WithMany("Items")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlgoJudge.Domain.Entities.Problem", "Problem")
                        .WithMany("ContentBatchItems")
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AlgoJudge.Domain.Entities.ProblemAuthoringRevision", "Revision")
                        .WithMany("ContentBatchItems")
                        .HasForeignKey("RevisionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Batch");

                    b.Navigation("Problem");

                    b.Navigation("Revision");
                });

            modelBuilder.Entity("AlgoJudge.Domain.Entities.ContentGenerationJob", b =>
                {
                    b.HasOne("AlgoJudge.Domain.Entities.ContentBatchItem", "BatchItem")
                        .WithMany("GenerationJobs")
                        .HasForeignKey("BatchItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AlgoJudge.Domain.Entities.ProblemAuthoringRevision", "Revision")
                        .WithMany("GenerationJobs")
                        .HasForeignKey("RevisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BatchItem");

                    b.Navigation("Revision");
                });

            modelBuilder.Entity("AlgoJudge.Domain.Entities.JudgeTestCase", b =>
                {
                    b.HasOne("AlgoJudge.Domain.Entities.Problem", "Problem")
                        .WithMany("JudgeTestCases")
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlgoJudge.Domain.Entities.PublishedSystemTestSuite", "SystemTestSuite")
                        .WithMany("TestCases")
                        .HasForeignKey("ProblemId", "SystemTestSuiteVersion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Problem");

                    b.Navigation("SystemTestSuite");
                });

            modelBuilder.Entity("AlgoJudge.Domain.Entities.ProblemAuthoringRevision", b =>
                {
                    b.HasOne("AlgoJudge.Domain.Entities.User", "OwnerUser")
                        .WithMany("AuthoringRevisions")
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AlgoJudge.Domain.Entities.Problem", "Problem")
                        .WithMany("AuthoringRevisions")
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OwnerUser");

                    b.Navigation("Problem");
                });

            modelBuilder.Entity("AlgoJudge.Domain.Entities.ProblemSample", b =>
                {
                    b.HasOne("AlgoJudge.Domain.Entities.Problem", "Problem")
                        .WithMany("Samples")
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Problem");
                });

            modelBuilder.Entity("AlgoJudge.Domain.Entities.ProblemTag", b =>
                {
                    b.HasOne("AlgoJudge.Domain.Entities.Problem", "Problem")
                        .WithMany("Tags")
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlgoJudge.Domain.Entities.Tag", "Tag")
                        .WithMany("Problems")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Problem");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("AlgoJudge.Domain.Entities.PublishedSystemTestSuite", b =>
                {
                    b.HasOne("AlgoJudge.Domain.Entities.Problem", "Problem")
                        .WithMany("SystemTestSuites")
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Problem");
                });

            modelBuilder.Entity("AlgoJudge.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("AlgoJudge.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AlgoJudge.Domain.Entities.Submission", b =>
                {
                    b.HasOne("AlgoJudge.Domain.Entities.Problem", "Problem")
                        .WithMany("Submissions")
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlgoJudge.Domain.Entities.User", "User")
                        .WithMany("Submissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Problem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AlgoJudge.Domain.Entities.ContentBatch", b =>
                {
                    b.Navigation("AuditEntries");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("AlgoJudge.Domain.Entities.ContentBatchItem", b =>
                {
                    b.Navigation("AuditEntries");

                    b.Navigation("GenerationJobs");
                });

            modelBuilder.Entity("AlgoJudge.Domain.Entities.Problem", b =>
                {
                    b.Navigation("AuthoringRevisions");

                    b.Navigation("CodeRuns");

                    b.Navigation("ContentBatchItems");

                    b.Navigation("JudgeTestCases");

                    b.Navigation("Samples");

                    b.Navigation("Submissions");

                    b.Navigation("SystemTestSuites");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("AlgoJudge.Domain.Entities.ProblemAuthoringRevision", b =>
                {
                    b.Navigation("CandidateTestCases");

                    b.Navigation("ContentBatchItems");

                    b.Navigation("GenerationJobs");
                });

            modelBuilder.Entity("AlgoJudge.Domain.Entities.PublishedSystemTestSuite", b =>
                {
                    b.Navigation("TestCases");
                });

            modelBuilder.Entity("AlgoJudge.Domain.Entities.Tag", b =>
                {
                    b.Navigation("Problems");
                });

            modelBuilder.Entity("AlgoJudge.Domain.Entities.User", b =>
                {
                    b.Navigation("AuthoringRevisions");

                    b.Navigation("CodeRuns");

                    b.Navigation("ContentBatchAuditEntries");

                    b.Navigation("ContentBatches");

                    b.Navigation("Submissions");
                });
#pragma warning restore 612, 618
        }
    }
}
