/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PagedResponseOfAdminProblemListItemResponse } from '../../models/paged-response-of-admin-problem-list-item-response';
import { ProblemStatus } from '../../models/problem-status';

export interface ApiInternalAdminProblemsGet$Json$Params {
  PageNumber?: (number | string);
  PageSize?: (number | string);
  Search?: string;
  Status?: ProblemStatus;
}

export function apiInternalAdminProblemsGet$Json(http: HttpClient, rootUrl: string, params?: ApiInternalAdminProblemsGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<PagedResponseOfAdminProblemListItemResponse>> {
  const rb = new RequestBuilder(rootUrl, apiInternalAdminProblemsGet$Json.PATH, 'get');
  if (params) {
    rb.query('PageNumber', params.PageNumber, {});
    rb.query('PageSize', params.PageSize, {});
    rb.query('Search', params.Search, {});
    rb.query('Status', params.Status, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PagedResponseOfAdminProblemListItemResponse>;
    })
  );
}

apiInternalAdminProblemsGet$Json.PATH = '/api/internal/admin/problems';
