/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AdminProblemResponse } from '../../models/admin-problem-response';

export interface ApiInternalAdminProblemsProblemIdGet$Json$Params {
  problemId: number;
}

export function apiInternalAdminProblemsProblemIdGet$Json(http: HttpClient, rootUrl: string, params: ApiInternalAdminProblemsProblemIdGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<AdminProblemResponse>> {
  const rb = new RequestBuilder(rootUrl, apiInternalAdminProblemsProblemIdGet$Json.PATH, 'get');
  if (params) {
    rb.path('problemId', params.problemId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AdminProblemResponse>;
    })
  );
}

apiInternalAdminProblemsProblemIdGet$Json.PATH = '/api/internal/admin/problems/{problemId}';
