/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ProblemDraftResponse } from '../../models/problem-draft-response';

export interface ApiInternalAdminProblemsProblemIdRevisionsPost$Json$Params {
  problemId: number;
}

export function apiInternalAdminProblemsProblemIdRevisionsPost$Json(http: HttpClient, rootUrl: string, params: ApiInternalAdminProblemsProblemIdRevisionsPost$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<ProblemDraftResponse>> {
  const rb = new RequestBuilder(rootUrl, apiInternalAdminProblemsProblemIdRevisionsPost$Json.PATH, 'post');
  if (params) {
    rb.path('problemId', params.problemId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ProblemDraftResponse>;
    })
  );
}

apiInternalAdminProblemsProblemIdRevisionsPost$Json.PATH = '/api/internal/admin/problems/{problemId}/revisions';
