/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PagedResponseOfAdminProblemListItemResponse } from '../../models/paged-response-of-admin-problem-list-item-response';
import { ProblemStatus } from '../../models/problem-status';

export interface ApiInternalAdminProblemsGet$Plain$Params {
  PageNumber?: (number | string);
  PageSize?: (number | string);
  Search?: string;
  Status?: ProblemStatus;
}

export function apiInternalAdminProblemsGet$Plain(http: HttpClient, rootUrl: string, params?: ApiInternalAdminProblemsGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<PagedResponseOfAdminProblemListItemResponse>> {
  const rb = new RequestBuilder(rootUrl, apiInternalAdminProblemsGet$Plain.PATH, 'get');
  if (params) {
    rb.query('PageNumber', params.PageNumber, {});
    rb.query('PageSize', params.PageSize, {});
    rb.query('Search', params.Search, {});
    rb.query('Status', params.Status, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PagedResponseOfAdminProblemListItemResponse>;
    })
  );
}

apiInternalAdminProblemsGet$Plain.PATH = '/api/internal/admin/problems';
