/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AuthoringRevisionStatus } from '../models/authoring-revision-status';
import { DifficultyLevel } from '../models/difficulty-level';
import { ProblemExecutionMode } from '../models/problem-execution-mode';
import { ProblemStatus } from '../models/problem-status';
export interface AdminProblemResponse {
  constraintsMarkdown?: string;
  createdAt?: string;
  difficulty?: DifficultyLevel;
  executionMode?: ProblemExecutionMode;
  id?: (number | string);
  judgeVersion?: (number | string);
  latestRevisionId?: (string | null);
  latestRevisionStatus?: (AuthoringRevisionStatus | null);
  memoryLimitKb?: (number | string);
  publishedAt?: (string | null);
  slug?: string;
  statementMarkdown?: string;
  status?: ProblemStatus;
  timeLimitMs?: (number | string);
  title?: string;
  updatedAt?: string;
}
