/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AuthoringRevisionStatus } from '../models/authoring-revision-status';
import { DifficultyLevel } from '../models/difficulty-level';
import { ProblemStatus } from '../models/problem-status';
export interface AdminProblemListItemResponse {
  difficulty?: DifficultyLevel;
  id?: (number | string);
  judgeVersion?: (number | string);
  latestRevisionId?: (string | null);
  latestRevisionStatus?: (AuthoringRevisionStatus | null);
  publishedAt?: (string | null);
  slug?: string;
  status?: ProblemStatus;
  title?: string;
  updatedAt?: string;
}
