/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ContentBatchCountsResponse {
  failed?: (number | string);
  generating?: (number | string);
  pending?: (number | string);
  published?: (number | string);
  ready?: (number | string);
  skipped?: (number | string);
  total?: (number | string);
}
