/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ContentBatchAuditResponse {
  action?: string;
  adminUserId?: string;
  createdAt?: string;
  id?: (number | string);
  itemId?: (string | null);
  problemId?: (number | string | null);
  result?: string;
  revisionId?: (string | null);
  safeFailureCategory?: (string | null);
}
