/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DifficultyLevel } from '../models/difficulty-level';
import { ProblemSampleRequest } from '../models/problem-sample-request';
export interface CreateProblemDraftRequest {
  constraintsMarkdown?: string;
  difficulty?: DifficultyLevel;
  memoryLimitKb?: (number | string);
  samples?: Array<ProblemSampleRequest>;
  slug?: string;
  statementMarkdown?: string;
  timeLimitMs?: (number | string);
  title?: string;
}
