/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CreateContentBatchItemRequest } from '../models/create-content-batch-item-request';
export interface CreateContentBatchRequest {
  catalogName?: string;
  items?: Array<CreateContentBatchItemRequest>;
}
