/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ContentBatchImportAction } from '../models/content-batch-import-action';
import { DifficultyLevel } from '../models/difficulty-level';
import { JsonElement } from '../models/json-element';
import { ProblemAuthoringDefinition } from '../models/problem-authoring-definition';
import { ProblemSampleRequest } from '../models/problem-sample-request';
export interface CreateContentBatchItemRequest {
  action?: ContentBatchImportAction;
  catalogPath?: string;
  constraintsMarkdown?: string;
  contentHash?: string;
  definition?: (ProblemAuthoringDefinition | null);
  difficulty?: DifficultyLevel;
  generatorParameters?: JsonElement;
  memoryLimitKb?: (number | string);
  samples?: Array<ProblemSampleRequest>;
  slug?: string;
  statementMarkdown?: string;
  tags?: Array<string>;
  timeLimitMs?: (number | string);
  title?: string;
  validationFailureCategory?: (string | null);
  validationFailureMessage?: (string | null);
}
