/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { FunctionValueType } from '../models/function-value-type';
export interface FunctionParameter {
  name?: string;
  type?: FunctionValueType;
}
