/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { FunctionParameter } from '../models/function-parameter';
import { FunctionValueType } from '../models/function-value-type';
export interface FunctionSignature {
  className?: string;
  methodName?: string;
  parameters?: Array<FunctionParameter>;
  returnType?: FunctionValueType;
}
