/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface GeneratedCaseReviewResponse {
  group?: string;
  killedWrongSolutions?: Array<string>;
  name?: string;
  ordinal?: (number | string);
  seed?: (number | string);
}
