/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { JsonElement } from '../models/json-element';
export interface HandwrittenCaseDefinition {
  arguments?: JsonElement;
  group?: string;
  name?: string;
}
