/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ContentBatchListItemResponse } from '../models/content-batch-list-item-response';
export interface PagedResponseOfContentBatchListItemResponse {
  items?: Array<ContentBatchListItemResponse>;
  pageNumber?: (number | string);
  pageSize?: (number | string);
  totalCount?: (number | string);
  totalPages?: (number | string);
}
