/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AdminProblemListItemResponse } from '../models/admin-problem-list-item-response';
export interface PagedResponseOfAdminProblemListItemResponse {
  items?: Array<AdminProblemListItemResponse>;
  pageNumber?: (number | string);
  pageSize?: (number | string);
  totalCount?: (number | string);
  totalPages?: (number | string);
}
