/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { FunctionSignature } from '../models/function-signature';
import { FunctionSourceDefinition } from '../models/function-source-definition';
import { GeneratorSourceDefinition } from '../models/generator-source-definition';
import { HandwrittenCaseDefinition } from '../models/handwritten-case-definition';
import { ProblemExecutionMode } from '../models/problem-execution-mode';
import { SuiteQualityPolicy } from '../models/suite-quality-policy';
import { WrongSolutionDefinition } from '../models/wrong-solution-definition';
export interface ProblemAuthoringDefinition {
  executionMode?: ProblemExecutionMode;
  functionSignature?: FunctionSignature;
  generator?: GeneratorSourceDefinition;
  handwrittenCases?: Array<HandwrittenCaseDefinition>;
  inputValidator?: GeneratorSourceDefinition;
  qualityPolicy?: SuiteQualityPolicy;
  referenceSolution?: FunctionSourceDefinition;
  schemaVersion?: (number | string);
  wrongSolutions?: Array<WrongSolutionDefinition>;
}
