/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { SuiteQualityGroupRequirement } from '../models/suite-quality-group-requirement';
export interface SuiteQualityPolicy {
  minimumCasesByGroup?: Array<SuiteQualityGroupRequirement>;
  minimumTestCaseCount?: (number | string);
  requireEachDeclaredWrongSolutionKilled?: boolean;
}
