/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HandwrittenCaseDefinition } from '../models/handwritten-case-definition';
export interface UpdateHandwrittenCasesRequest {
  cases?: Array<HandwrittenCaseDefinition>;
}
