/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { FunctionSignature } from '../models/function-signature';
export interface UpdateFunctionSignatureRequest {
  signature?: FunctionSignature;
}
