/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { SuiteQualityPolicy } from '../models/suite-quality-policy';
export interface UpdateSuiteQualityPolicyRequest {
  qualityPolicy?: SuiteQualityPolicy;
}
