/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { FunctionSourceDefinition } from '../models/function-source-definition';
import { GeneratorSourceDefinition } from '../models/generator-source-definition';
import { WrongSolutionDefinition } from '../models/wrong-solution-definition';
export interface UpdateAuthoringSourcesRequest {
  generator?: GeneratorSourceDefinition;
  inputValidator?: GeneratorSourceDefinition;
  referenceSolution?: FunctionSourceDefinition;
  wrongSolutions?: Array<WrongSolutionDefinition>;
}
